### ISSUE TITLE
Can you provide a dockerized image of this, published on docker hub?

### ISSUE THREAD

**Issue by djangofan** [n-riesco/ijavascript#196]
Can you provide a dockerized image of this, published on docker hub?

Similar to :  https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html

Just want something more user friendly where I can just launch with `docker-compose up -d` with a docker-compose.yml like this:

version: "3"
services:

```
  jupyter:
    image: n-riesco/ijavascript-notebook:latest
    ports:
      - "10000:8888"
    links:
      - postgres
    volumes:
      - "/Users/me/Docker/ijavascript-jupyter/work:/home/n-riesco/work"
```
